# Generated by Django 4.2.13 on 2025-09-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_active'),
        ('orders', '0002_alter_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('cooking', 'Cooking'), ('done', 'Done')], default='ordered', max_length=20, null=True),
        ),
    ]
