# Generated by Django 4.2.13 on 2025-09-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('cooking', 'Cooking'), ('done', 'Done')], default='ordered', max_length=20, null=True),
        ),
    ]
