# Generated by Django 4.2.13 on 2025-09-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockin_user_alter_stockout_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockout',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='stockin',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='min_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Minimum stock threshold for alert', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current price per unit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price for this quantity', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='reason',
            field=models.CharField(blank=True, choices=[('processing', 'Processing/Cooking'), ('cancel', 'Cancelled'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
