# Generated by Django 4.2.13 on 2025-09-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockin_options_alter_stockout_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='user_id',
            new_name='user',
        ),
    ]
