# Generated by Django 4.2.13 on 2025-09-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockin_options_alter_stockout_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('liter', 'Liter'), ('piece', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can'), ('set', 'Set'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
