# Generated by Django 4.2.13 on 2025-10-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_user_order_user_and_more'),
        ('inventory', '0004_rename_user_id_stockin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the stock-out', null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Order item that triggered this stock-out (for cooking reason)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='reason',
            field=models.CharField(blank=True, choices=[('cooking', 'Cooking'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
