# Generated by Django 4.2.13 on 2025-09-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_active'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('merged', 'Merged')], default='available', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TableMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('separated_at', models.DateTimeField(blank=True, help_text='When tables were separated', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the merge is currently active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_merges', to='accounts.user')),
                ('main_table', models.ForeignKey(help_text='Main table that other tables are merged into', on_delete=django.db.models.deletion.CASCADE, related_name='main_merges', to='tables.table')),
                ('merged_tables', models.ManyToManyField(help_text='Tables that are merged into the main table', related_name='merged_into', to='tables.table')),
                ('separated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_separations', to='accounts.user')),
            ],
            options={
                'db_table': 'table_merges',
                'ordering': ['-created_at'],
            },
        ),
    ]
